apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cago.fullname" . }}
data:
  config.yaml: |
    source: etcd
    env: {{ .Values.appConfig.env }}
    debug: {{ .Values.appConfig.debug }}
    version: 1.0.0
    etcd:
      prefix: /config
      endpoints:
        - etcd-config.core.svc.cluster.local:2379
      username: {{ .Values.etcdConfig.username }}
      password: {{ .Values.etcdConfig.password }}
