# 支持灰度发布,使用istio-gateway实现流量控制
{{- if .Values.istio.enabled -}}}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "cago.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . | quote }}
        {{- end }}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "cago.fullname" . }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ include "cago.fullname" . }}-gateway
  http:
    - match:
        {{- toYaml .Values.istio.match | nindent 8 }}}
      route:
        - destination:
            port:
              number: 80
            host: {{ include "cago.fullname" . }}

{{- end }}