apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cago.fullname" . }}-resource-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 20Gi
