version: '3'

services:

  redis:
    image: redis
    volumes:
      - ./.docker/redis:/data
    ports:
      - 6379:6379

  mysql:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=scriptlist
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=hostname # hostname需要修改成实际的ip
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
