// Code generated by MockGen. DO NOT EDIT.
// Source: ./script_group_member.go
//
// Generated by this command:
//
//	mockgen -source=./script_group_member.go -destination=./mock/script_group_member.go
//

// Package mock_script_repo is a generated GoMock package.
package mock_script_repo

import (
	context "context"
	reflect "reflect"

	httputils "github.com/codfrm/cago/pkg/utils/httputils"
	script_entity "github.com/scriptscat/scriptlist/internal/model/entity/script_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptGroupMemberRepo is a mock of ScriptGroupMemberRepo interface.
type MockScriptGroupMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockScriptGroupMemberRepoMockRecorder
}

// MockScriptGroupMemberRepoMockRecorder is the mock recorder for MockScriptGroupMemberRepo.
type MockScriptGroupMemberRepoMockRecorder struct {
	mock *MockScriptGroupMemberRepo
}

// NewMockScriptGroupMemberRepo creates a new mock instance.
func NewMockScriptGroupMemberRepo(ctrl *gomock.Controller) *MockScriptGroupMemberRepo {
	mock := &MockScriptGroupMemberRepo{ctrl: ctrl}
	mock.recorder = &MockScriptGroupMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptGroupMemberRepo) EXPECT() *MockScriptGroupMemberRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScriptGroupMemberRepo) Create(ctx context.Context, scriptGroupMember *script_entity.ScriptGroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, scriptGroupMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScriptGroupMemberRepoMockRecorder) Create(ctx, scriptGroupMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).Create), ctx, scriptGroupMember)
}

// Delete mocks base method.
func (m *MockScriptGroupMemberRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScriptGroupMemberRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockScriptGroupMemberRepo) Find(ctx context.Context, id int64) (*script_entity.ScriptGroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*script_entity.ScriptGroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScriptGroupMemberRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).Find), ctx, id)
}

// FindByUserId mocks base method.
func (m *MockScriptGroupMemberRepo) FindByUserId(ctx context.Context, scriptId, userId int64) ([]*script_entity.ScriptGroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, scriptId, userId)
	ret0, _ := ret[0].([]*script_entity.ScriptGroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockScriptGroupMemberRepoMockRecorder) FindByUserId(ctx, scriptId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).FindByUserId), ctx, scriptId, userId)
}

// FindPage mocks base method.
func (m *MockScriptGroupMemberRepo) FindPage(ctx context.Context, page httputils.PageRequest) ([]*script_entity.ScriptGroupMember, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, page)
	ret0, _ := ret[0].([]*script_entity.ScriptGroupMember)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockScriptGroupMemberRepoMockRecorder) FindPage(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).FindPage), ctx, page)
}

// Update mocks base method.
func (m *MockScriptGroupMemberRepo) Update(ctx context.Context, scriptGroupMember *script_entity.ScriptGroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, scriptGroupMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScriptGroupMemberRepoMockRecorder) Update(ctx, scriptGroupMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScriptGroupMemberRepo)(nil).Update), ctx, scriptGroupMember)
}
