# 外部暴露暂时只有一台机器, 先使用ingress->gateway的方式
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.project }}
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: k3s-backup-nginx
  tls:
    - hosts:
        - scriptcat.org
      secretName: scriptcat-org-tls
  rules:
    - host: scriptcat.org
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: istio-ingressgateway
                port:
                  name: http
