// Code generated by MockGen. DO NOT EDIT.
// Source: ./audit_log.go
//
// Generated by this command:
//
//	mockgen -source=./audit_log.go -destination=./mock/audit_log.go
//

// Package mock_audit_repo is a generated GoMock package.
package mock_audit_repo

import (
	context "context"
	reflect "reflect"

	audit_entity "github.com/scriptscat/scriptlist/internal/model/entity/audit_entity"
	audit_repo "github.com/scriptscat/scriptlist/internal/repository/audit_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepo is a mock of AuditLogRepo interface.
type MockAuditLogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepoMockRecorder
	isgomock struct{}
}

// MockAuditLogRepoMockRecorder is the mock recorder for MockAuditLogRepo.
type MockAuditLogRepoMockRecorder struct {
	mock *MockAuditLogRepo
}

// NewMockAuditLogRepo creates a new mock instance.
func NewMockAuditLogRepo(ctrl *gomock.Controller) *MockAuditLogRepo {
	mock := &MockAuditLogRepo{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepo) EXPECT() *MockAuditLogRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogRepo) Create(ctx context.Context, auditLog *audit_entity.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, auditLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepoMockRecorder) Create(ctx, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepo)(nil).Create), ctx, auditLog)
}

// FindPage mocks base method.
func (m *MockAuditLogRepo) FindPage(ctx context.Context, opts *audit_repo.ListOptions) ([]*audit_entity.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, opts)
	ret0, _ := ret[0].([]*audit_entity.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockAuditLogRepoMockRecorder) FindPage(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockAuditLogRepo)(nil).FindPage), ctx, opts)
}
