// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mock/user.go
//

// Package mock_user_entity is a generated GoMock package.
package mock_user_entity
