// Code generated by MockGen. DO NOT EDIT.
// Source: ./script_report.go
//
// Generated by this command:
//
//	mockgen -source=./script_report.go -destination=./mock/script_report.go -package=mock_report_repo
//

// Package mock_report_repo is a generated GoMock package.
package mock_report_repo

import (
	context "context"
	reflect "reflect"

	httputils "github.com/cago-frame/cago/pkg/utils/httputils"
	report_entity "github.com/scriptscat/scriptlist/internal/model/entity/report_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptReportRepo is a mock of ScriptReportRepo interface.
type MockScriptReportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockScriptReportRepoMockRecorder
	isgomock struct{}
}

// MockScriptReportRepoMockRecorder is the mock recorder for MockScriptReportRepo.
type MockScriptReportRepoMockRecorder struct {
	mock *MockScriptReportRepo
}

// NewMockScriptReportRepo creates a new mock instance.
func NewMockScriptReportRepo(ctrl *gomock.Controller) *MockScriptReportRepo {
	mock := &MockScriptReportRepo{ctrl: ctrl}
	mock.recorder = &MockScriptReportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptReportRepo) EXPECT() *MockScriptReportRepoMockRecorder {
	return m.recorder
}

// CountByScript mocks base method.
func (m *MockScriptReportRepo) CountByScript(ctx context.Context, scriptId int64, status int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByScript", ctx, scriptId, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByScript indicates an expected call of CountByScript.
func (mr *MockScriptReportRepoMockRecorder) CountByScript(ctx, scriptId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByScript", reflect.TypeOf((*MockScriptReportRepo)(nil).CountByScript), ctx, scriptId, status)
}

// Create mocks base method.
func (m *MockScriptReportRepo) Create(ctx context.Context, report *report_entity.ScriptReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScriptReportRepoMockRecorder) Create(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScriptReportRepo)(nil).Create), ctx, report)
}

// Delete mocks base method.
func (m *MockScriptReportRepo) Delete(ctx context.Context, scriptId, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, scriptId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScriptReportRepoMockRecorder) Delete(ctx, scriptId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScriptReportRepo)(nil).Delete), ctx, scriptId, id)
}

// Find mocks base method.
func (m *MockScriptReportRepo) Find(ctx context.Context, scriptId, id int64) (*report_entity.ScriptReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, scriptId, id)
	ret0, _ := ret[0].(*report_entity.ScriptReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScriptReportRepoMockRecorder) Find(ctx, scriptId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScriptReportRepo)(nil).Find), ctx, scriptId, id)
}

// FindPage mocks base method.
func (m *MockScriptReportRepo) FindPage(ctx context.Context, scriptId int64, status int32, page httputils.PageRequest) ([]*report_entity.ScriptReport, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, scriptId, status, page)
	ret0, _ := ret[0].([]*report_entity.ScriptReport)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockScriptReportRepoMockRecorder) FindPage(ctx, scriptId, status, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockScriptReportRepo)(nil).FindPage), ctx, scriptId, status, page)
}

// Update mocks base method.
func (m *MockScriptReportRepo) Update(ctx context.Context, report *report_entity.ScriptReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScriptReportRepoMockRecorder) Update(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScriptReportRepo)(nil).Update), ctx, report)
}
