// Code generated by MockGen. DO NOT EDIT.
// Source: ./script_report_comment.go
//
// Generated by this command:
//
//	mockgen -source=./script_report_comment.go -destination=./mock/script_report_comment.go -package=mock_report_repo
//

// Package mock_report_repo is a generated GoMock package.
package mock_report_repo

import (
	context "context"
	reflect "reflect"

	report_entity "github.com/scriptscat/scriptlist/internal/model/entity/report_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptReportCommentRepo is a mock of ScriptReportCommentRepo interface.
type MockScriptReportCommentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockScriptReportCommentRepoMockRecorder
	isgomock struct{}
}

// MockScriptReportCommentRepoMockRecorder is the mock recorder for MockScriptReportCommentRepo.
type MockScriptReportCommentRepoMockRecorder struct {
	mock *MockScriptReportCommentRepo
}

// NewMockScriptReportCommentRepo creates a new mock instance.
func NewMockScriptReportCommentRepo(ctrl *gomock.Controller) *MockScriptReportCommentRepo {
	mock := &MockScriptReportCommentRepo{ctrl: ctrl}
	mock.recorder = &MockScriptReportCommentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptReportCommentRepo) EXPECT() *MockScriptReportCommentRepoMockRecorder {
	return m.recorder
}

// CountByReport mocks base method.
func (m *MockScriptReportCommentRepo) CountByReport(ctx context.Context, reportId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByReport", ctx, reportId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByReport indicates an expected call of CountByReport.
func (mr *MockScriptReportCommentRepoMockRecorder) CountByReport(ctx, reportId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByReport", reflect.TypeOf((*MockScriptReportCommentRepo)(nil).CountByReport), ctx, reportId)
}

// Create mocks base method.
func (m *MockScriptReportCommentRepo) Create(ctx context.Context, comment *report_entity.ScriptReportComment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScriptReportCommentRepoMockRecorder) Create(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScriptReportCommentRepo)(nil).Create), ctx, comment)
}

// Delete mocks base method.
func (m *MockScriptReportCommentRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScriptReportCommentRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScriptReportCommentRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockScriptReportCommentRepo) Find(ctx context.Context, reportId, id int64) (*report_entity.ScriptReportComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, reportId, id)
	ret0, _ := ret[0].(*report_entity.ScriptReportComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockScriptReportCommentRepoMockRecorder) Find(ctx, reportId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockScriptReportCommentRepo)(nil).Find), ctx, reportId, id)
}

// FindAll mocks base method.
func (m *MockScriptReportCommentRepo) FindAll(ctx context.Context, reportId int64) ([]*report_entity.ScriptReportComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, reportId)
	ret0, _ := ret[0].([]*report_entity.ScriptReportComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockScriptReportCommentRepoMockRecorder) FindAll(ctx, reportId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockScriptReportCommentRepo)(nil).FindAll), ctx, reportId)
}
