basePath: /api/v2
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
info:
  title: 脚本站 API 文档
  version: 2.0.0
paths: {}
swagger: "2.0"
