basePath: /api/v2
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  httputils.PageRequest:
    properties:
      limit,default=20:
        type: integer
      page,default=1:
        type: integer
    type: object
  httputils.PageResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Script'
          type: object
        type: array
      total:
        type: integer
    type: object
  model.AdminLevel:
    description: |-
      AdminLevel enum type:
      - Admin: 1
      - SuperModerator: 2
      - Moderator: 3
    enum:
    - 1
    - 2
    - 3
    type: integer
  script.CodeResponse:
    properties:
      archive:
        type: integer
      avatar:
        type: string
      category:
        items:
          $ref: '#/definitions/script.ScriptCategoryList'
        type: array
      content,omitempty:
        type: string
      createtime:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      post_id:
        type: integer
      public:
        type: integer
      score:
        type: integer
      score_num:
        type: integer
      script:
        $ref: '#/definitions/script.ScriptCode'
      status:
        type: integer
      today_install:
        type: integer
      total_install:
        type: integer
      type:
        type: integer
      unwell:
        type: integer
      updatetime:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
  script.CreateRequest:
    properties:
      changelog:
        type: string
      code:
        type: string
      content:
        type: string
      definition:
        type: string
      description:
        type: string
      name:
        type: string
      public:
        $ref: '#/definitions/script_entity.Public'
        description: 公开类型：1 公开 2 半公开
      type:
        $ref: '#/definitions/script_entity.Type'
        description: 脚本类型：1 用户脚本 2 脚本引用库 3 订阅脚本(不支持)
      unwell:
        $ref: '#/definitions/script_entity.UnwellContent'
        description: '不适内容: 1 不适 2 适用'
      version:
        type: string
    type: object
  script.CreateResponse:
    properties:
      id:
        type: integer
    type: object
  script.InfoResponse:
    properties:
      archive:
        type: integer
      avatar:
        type: string
      category:
        items:
          $ref: '#/definitions/script.ScriptCategoryList'
        type: array
      content,omitempty:
        type: string
      createtime:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      post_id:
        type: integer
      public:
        type: integer
      score:
        type: integer
      score_num:
        type: integer
      script:
        $ref: '#/definitions/script.ScriptCode'
      status:
        type: integer
      today_install:
        type: integer
      total_install:
        type: integer
      type:
        type: integer
      unwell:
        type: integer
      updatetime:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
  script.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Script'
          type: object
        type: array
      total:
        type: integer
    type: object
  script.MigrateEsRequest:
    type: object
  script.MigrateEsResponse:
    type: object
  script.Script:
    properties:
      archive:
        type: integer
      avatar:
        type: string
      category:
        items:
          $ref: '#/definitions/script.ScriptCategoryList'
        type: array
      content,omitempty:
        type: string
      createtime:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      post_id:
        type: integer
      public:
        type: integer
      score:
        type: integer
      score_num:
        type: integer
      script:
        $ref: '#/definitions/script.ScriptCode'
      status:
        type: integer
      today_install:
        type: integer
      total_install:
        type: integer
      type:
        type: integer
      unwell:
        type: integer
      updatetime:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
  script.ScriptCategoryList:
    properties:
      createtime:
        type: integer
      id:
        type: integer
      name:
        type: string
      num:
        description: 本分类下脚本数量
        type: integer
      sort:
        type: integer
      updatetime:
        type: integer
    type: object
  script.ScriptCode:
    properties:
      avatar:
        type: string
      changelog:
        type: string
      code,omitempty:
        type: string
      createtime:
        type: integer
      definition,omitempty:
        type: string
      id:
        type: integer
      meta,omitempty:
        type: string
      meta_json:
        type: object
      script_id:
        type: integer
      status:
        type: integer
      user_id:
        type: integer
      username:
        type: string
      version:
        type: string
    type: object
  script.StateResponse:
    properties:
      watch:
        $ref: '#/definitions/script_entity.ScriptWatchLevel'
    type: object
  script.UpdateCodeRequest:
    properties:
      changelog:
        type: string
      code:
        type: string
      content:
        type: string
      definition:
        type: string
      id:
        type: integer
      public:
        $ref: '#/definitions/script_entity.Public'
        description: 公开类型：1 公开 2 半公开
      unwell:
        $ref: '#/definitions/script_entity.UnwellContent'
      version:
        description: |-
          Name string `form:"name" binding:"max=128" label:"库的名字"`
          Description string `form:"description" binding:"max=102400" label:"库的描述"`
        type: string
    type: object
  script.UpdateCodeResponse:
    type: object
  script.VersionCodeResponse:
    properties:
      archive:
        type: integer
      avatar:
        type: string
      category:
        items:
          $ref: '#/definitions/script.ScriptCategoryList'
        type: array
      content,omitempty:
        type: string
      createtime:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      post_id:
        type: integer
      public:
        type: integer
      score:
        type: integer
      score_num:
        type: integer
      script:
        $ref: '#/definitions/script.ScriptCode'
      status:
        type: integer
      today_install:
        type: integer
      total_install:
        type: integer
      type:
        type: integer
      unwell:
        type: integer
      updatetime:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
  script.VersionListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Script'
          type: object
        type: array
      total:
        type: integer
    type: object
  script.WatchRequest:
    properties:
      id:
        type: integer
      watch:
        $ref: '#/definitions/script_entity.ScriptWatchLevel'
    type: object
  script.WatchResponse:
    type: object
  script_entity.Public:
    description: |-
      Public enum type:
      - PublicScript: 1
      - PrivateScript: 2
    enum:
    - 1
    - 2
    type: integer
  script_entity.ScriptWatchLevel:
    description: |-
      ScriptWatchLevel enum type:
      - ScriptWatchLevelNone: 1
      - ScriptWatchLevelVersion: 2
      - ScriptWatchLevelIssue: 3
      - ScriptWatchLevelIssueComment: 4
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
  script_entity.Type:
    description: |-
      Type enum type:
      - UserscriptType: 1
      - SubscribeType: 2
      - LibraryType: 3
    enum:
    - 1
    - 2
    - 3
    type: integer
  script_entity.UnwellContent:
    description: |-
      UnwellContent enum type:
      - Unwell: 1
      - Well: 2
    enum:
    - 1
    - 2
    type: integer
  user.CurrentUserResponse:
    properties:
      avatar:
        type: string
      email_status:
        type: integer
      is_admin:
        $ref: '#/definitions/model.AdminLevel'
      uid:
        type: integer
      username:
        type: string
    type: object
  user.InfoResponse:
    properties:
      avatar:
        type: string
      email_status:
        type: integer
      is_admin:
        $ref: '#/definitions/model.AdminLevel'
      uid:
        type: integer
      username:
        type: string
    type: object
  user.OAuthCallbackResponse:
    properties:
      redirect_uri:
        type: string
      uid:
        type: integer
    type: object
  user_entity.UserInfo:
    properties:
      avatar:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
info:
  title: 脚本站 API 文档
  version: 2.0.0
paths:
  /login/oauth:
    get:
      consumes:
      - application/json
      description: 第三方登录
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: redirect_uri
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.OAuthCallbackResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 第三方登录
      tags:
      - user
  /scripts:
    get:
      consumes:
      - application/json
      description: 获取脚本列表
      parameters:
      - in: query
        name: keyword
        type: string
      - description: '0:全部 1: 脚本 2: 库 3: 后台脚本 4: 定时脚本'
        in: query
        name: script_type,default=0
        type: integer
      - in: query
        name: sort,default=today_download
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本列表
      tags:
      - script
    post:
      consumes:
      - application/json
      description: 创建脚本
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.CreateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建脚本
      tags:
      - script
  /scripts/{id}:
    get:
      consumes:
      - application/json
      description: 获取脚本信息
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.InfoResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本信息
      tags:
      - script
  /scripts/{id}/code:
    get:
      consumes:
      - application/json
      description: 获取脚本代码信息
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.CodeResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本代码信息
      tags:
      - script
    put:
      consumes:
      - application/json
      description: 更新脚本/库代码
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.UpdateCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.UpdateCodeResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 更新脚本/库代码
      tags:
      - script
  /scripts/{id}/state:
    get:
      consumes:
      - application/json
      description: 获取脚本状态,脚本关注等
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.StateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本状态,脚本关注等
      tags:
      - script
  /scripts/{id}/versions:
    get:
      consumes:
      - application/json
      description: 获取版本列表
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.VersionListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取版本列表
      tags:
      - script
  /scripts/{id}/versions/{version}/code:
    get:
      consumes:
      - application/json
      description: 获取指定版本代码
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.VersionCodeResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取指定版本代码
      tags:
      - script
  /scripts/{id}/watch:
    post:
      consumes:
      - application/json
      description: 关注脚本
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.WatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.WatchResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 关注脚本
      tags:
      - script
  /scripts/migrate/es:
    post:
      consumes:
      - application/json
      description: 全量迁移数据到es
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.MigrateEsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.MigrateEsResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 全量迁移数据到es
      tags:
      - script
  /users:
    get:
      consumes:
      - application/json
      description: 获取当前登录的用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取当前登录的用户信息
      tags:
      - user
  /users/{uid}/info:
    get:
      consumes:
      - application/json
      description: 获取指定用户信息
      parameters:
      - in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.InfoResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取指定用户信息
      tags:
      - user
swagger: "2.0"
