basePath: /api/v2
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  httputils.PageRequest:
    properties:
      limit:
        type: integer
      page:
        type: integer
    type: object
  httputils.PageResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  script.CreateRequest:
    properties:
      changelog:
        type: string
      code:
        type: string
      content:
        type: string
      definition:
        type: string
      description:
        type: string
      name:
        type: string
      public:
        $ref: '#/definitions/script.Public'
        description: 公开类型：1 公开 2 半公开
      type:
        $ref: '#/definitions/script.Type'
        description: 脚本类型：1 用户脚本 2 脚本引用库 3 订阅脚本(不支持)
      unwell:
        $ref: '#/definitions/script.UnwellContent'
        description: '不适内容: 1 不适 2 适用'
      version:
        type: string
    type: object
  script.CreateResponse:
    properties:
      id:
        type: integer
    type: object
  script.Item:
    properties:
      id:
        type: integer
    type: object
  script.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  script.MigrateEsRequest:
    type: object
  script.MigrateEsResponse:
    type: object
  script.Public:
    description: |-
      Public enum type:
      - PublicScript: 1
      - PrivateScript: 2
    enum:
    - 1
    - 2
    type: integer
  script.Type:
    description: |-
      Type enum type:
      - UserscriptType: 1
      - SubscribeType: 2
      - LibraryType: 3
    enum:
    - 1
    - 2
    - 3
    type: integer
  script.UnwellContent:
    description: |-
      UnwellContent enum type:
      - Unwell: 1
      - Well: 2
    enum:
    - 1
    - 2
    type: integer
  script.UpdateCodeRequest:
    properties:
      changelog:
        type: string
      code:
        type: string
      content:
        type: string
      definition:
        type: string
      id:
        type: integer
      public:
        $ref: '#/definitions/script.Public'
        description: 公开类型：1 公开 2 半公开
      unwell:
        $ref: '#/definitions/script.UnwellContent'
      version:
        description: |-
          Name string `form:"name" binding:"max=128" label:"库的名字"`
          Description string `form:"description" binding:"max=102400" label:"库的描述"`
        type: string
    type: object
  script.UpdateCodeResponse:
    type: object
  user.CurrentUserResponse:
    properties:
      avatar:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  user.InfoResponse:
    properties:
      avatar:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  user.OAuthCallbackResponse:
    properties:
      redirect_uri:
        type: string
      uid:
        type: integer
    type: object
info:
  title: 脚本站 API 文档
  version: 2.0.0
paths:
  /login/oauth:
    get:
      consumes:
      - application/json
      description: 第三方登录
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: redirect_uri
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.OAuthCallbackResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 第三方登录
      tags:
      - user
  /script:
    get:
      consumes:
      - application/json
      description: 获取脚本列表
      parameters:
      - in: query
        name: keyword
        type: string
      - description: '1: 脚本 2: 库 3: 后台脚本 4: 定时脚本'
        in: query
        name: type
        type: integer
      - in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本列表
      tags:
      - script
    post:
      consumes:
      - application/json
      description: 创建脚本
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.CreateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建脚本
      tags:
      - script
  /script/{id}/code:
    put:
      consumes:
      - application/json
      description: 更新脚本/库代码
      parameters:
      - name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.UpdateCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.UpdateCodeResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 更新脚本/库代码
      tags:
      - script
  /scripts/migrate/es:
    post:
      consumes:
      - application/json
      description: 全量迁移数据到es
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/script.MigrateEsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.MigrateEsResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 全量迁移数据到es
      tags:
      - script
  /user:
    get:
      consumes:
      - application/json
      description: 获取当前登录的用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取当前登录的用户信息
      tags:
      - user
  /user/{uid}/info:
    get:
      consumes:
      - application/json
      description: 获取指定用户信息
      parameters:
      - in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.InfoResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取指定用户信息
      tags:
      - user
swagger: "2.0"
