basePath: /api/v2
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  httputils.PageResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  script.Item:
    properties:
      id:
        type: integer
    type: object
  script.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/script.Item'
          type: object
        type: array
      o2313:
        type: string
      total:
        type: integer
    type: object
  user.CurrentUserResponse:
    properties:
      avatar:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  user.InfoResponse:
    properties:
      avatar:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  user.OAuthCallbackResponse:
    properties:
      redirect_uri:
        type: string
      uid:
        type: integer
    type: object
info:
  title: 脚本站 API 文档
  version: 2.0.0
paths:
  /login/oauth:
    get:
      consumes:
      - application/json
      description: 第三方登录
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: redirect_uri
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.OAuthCallbackResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 第三方登录
  /script/list:
    get:
      consumes:
      - application/json
      description: 获取脚本列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/script.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本列表
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取当前登录的用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取当前登录的用户信息
  /user/info/{uid}:
    get:
      consumes:
      - application/json
      description: 获取指定用户信息
      parameters:
      - in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.InfoResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取指定用户信息
swagger: "2.0"
